name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          port: 22
          script_stop: true

          script: |
            set -e

            echo "======================================"
            echo "Starting KKV Backend Deployment"
            echo "======================================"

            cd /home/ubuntu/kkv-web/backend

            echo "Pulling latest code..."
            git restore package-lock.json
            git pull origin main

            echo "Installing dependencies..."
            npm ci

            echo "Restarting KKV backend..."
            pm2 restart kkv-backend --update-env

            echo "Checking PM2 status..."
            pm2 status

            echo "======================================"
            echo "Deployment Completed Successfully!"
<<<<<<< HEAD
            echo "======================================"
=======
            echo "======================================"
>>>>>>> b0d2a6a (Update project)
